name: Reward Payout

on:
  pull_request:
    types:
      - closed

jobs:
  reward_payout:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is merged
      id: pr_merged
      run: echo "merged=true" >> $GITHUB_ENV

    - name: Initiate Payout
      if: steps.pr_merged.outputs.merged == 'true'
      env:
        CHIMONEY_API_KEY: ${{ secrets.CHIMONEY_API_KEY }}
      run: |
        PR_NUMBER="${{ github.event.pull_request.number }}"
        USER="${{ github.event.pull_request.user.login }}"
        AMOUNT="$2"

        # Get maintainers of repo
        MAINTAINERS=$(curl -s -X GET \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/Pinaka-Pani-18/testing/collaborators?per_page=100" | jq -r '.[].login')

        # Comment on the PR mentioning maintainers and asking them to send a reward
        COMMENT="PR Merged by @${USER}. Please send them Chimoney to cash out to a bank account, gift card, and other options."

        for MAINTAINER in $MAINTAINERS; do
          COMMENT="@${MAINTAINER} $COMMENT"
        done

        curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\":\"${COMMENT}\"}" \
          "https://api.github.com/repos/Pinaka-Pani-18/testing/issues/${PR_NUMBER}/comments"

        # Wait for maintainer response
        while true; do
          sleep 60
          response=$(curl -s -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Pinaka-Pani-18/testing/issues/${PR_NUMBER}/comments")

          if [[ "$response" =~ "@chimoney_bot send @${USER} \$[0-9]+" ]]; then
            break
          fi
        done

        # Get username and amount from response
        USER=$(echo "$response" | grep "@chimoney_bot send @${USER} \$[0-9]+" | sed -E 's/.*@chimoney_bot send @(.*) \$[0-9]+/\1/')
        AMOUNT=$(echo "$response" | grep "@chimoney_bot send @${USER} \$[0-9]+" | sed -E 's/.*@chimoney_bot send @(.*) \$([0-9]+)/\2/')

        # Initiate Chimoney payout using the updated API
        payout_request='{
          "chimoneys": [
            {
              "email": "pinakapani1806@gmail.com",
              "phone": "+916300760104",
              "valueInUSD": 10,
              "twitter": "@pinakapani06"
            }
          ]
        }'

        response=$(curl --request POST \
          --url https://api-v2-sandbox.chimoney.io/v0.2/payouts/initiate-chimoney \
          --header "X-API-KEY: $CHIMONEY_API_KEY" \
          --header 'accept: application/json' \
          --header 'content-type: application/json' \
          --data "$payout_request")

        # Log the response for debugging
        echo "Chimoney API Response: $response"

        # Check if the response contains a payout link
        payout_link=$(echo "$response" | jq -r '.payout_link')

        if [ -n "$payout_link" ]; then
          # Respond with the payment link
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"Payment link: <${payout_link}>\"}" \
            "https://api.github.com/repos/Pinaka-Pani-18/testing/issues/${PR_NUMBER}/comments"
        fi
